-- indexing in sql
select * from Employee;

-- create index based on salary
CREATE INDEX IX_EMPLOYEE_SALARY
ON EMPLOYEE (SALARY ASC);

EXECUTE SP_HELPINDEX EMPLOYEE;

--create clustered index
CREATE CLUSTERED INDEX IX_EMPLOYEE_GENDER_SALARY
ON EMPLOYEE(GENDER DESC,SALARY ASC);

--CREATE NON-CLUSTERED INDEX
CREATE NONCLUSTERED INDEX IX_EMPLOYEE_NAME
ON EMPLOYEE(NAME);

-- CREATE UNIQUE NON CLUSTERED INDEX
CREATE UNIQUE NONCLUSTERED INDEX IX_EMPLOYEE_UNIQUE_NAME
ON EMPLOYEE([NAME]);

EXECUTE SP_HELPINDEX EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE SALARY >5000;

SELECT * FROM EMPLOYEE ORDER BY NAME;